# Generated by Django 2.1.2 on 2019-04-18 08:54

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployexecution',
            name='extra_vars',
            field=common.models.JsonDictTextField(default={}),
        ),
    ]
