# Generated by Django 2.1.2 on 2019-04-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0002_deployexecution_extra_vars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcluster',
            name='executions',
        ),
    ]
