# Generated by Django 2.1.2 on 2019-04-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0003_remove_abstractcluster_executions'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractcluster',
            name='executions',
            field=models.ManyToManyField(to='openshift_base.DeployExecution'),
        ),
    ]
