# Generated by Django 2.1.2 on 2019-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0004_abstractcluster_executions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcluster',
            name='executions',
        ),
        migrations.AddField(
            model_name='deployexecution',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
