# Generated by Django 2.1.2 on 2019-04-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0005_auto_20190419_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployexecution',
            name='current_play',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
