# Generated by Django 2.1.2 on 2019-04-12 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ansible_api', '0002_auto_20190305_0555'),
    ]

    def forwards_func(apps, schema_editor):
        Project = apps.get_model("ansible_api", "Project")
        db_alias = schema_editor.connection.alias
        Project.objects.using(db_alias).bulk_create([
            Project(name='storage_default'),
        ])

    def reverse_func(apps, schema_editor):
        Project = apps.get_model("ansible_api", "Project")
        db_alias = schema_editor.connection.alias
        Project.objects.using(db_alias).filter(name='storage_default').delete()

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
