# Generated by Django 2.1.2 on 2019-04-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_storage', '0001_initial'),
        ('openshift_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='storages',
            field=models.ManyToManyField(to='openshift_storage.StorageCluster'),
        ),
    ]
